# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: sklep_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: sklep_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sklep_production
  pool: 5
  timeout: 5000
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
